{% set name = "mhealpy" %}
{% set version = "0.3.7" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://files.pythonhosted.org/packages/source/{{ name[0] }}/{{ name }}/mhealpy-{{ version }}.tar.gz
  sha256: 96492082f05c360291cccf37f372e567d8f3a9fa6b0cc01d5fbb972d5c2a6a1f

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python {{ python_min }}
    - setuptools
    - pip
  run:
    - python >={{ python_min }}
    - healpy
    - matplotlib-base

test:
  imports:
    - mhealpy
    - mhealpy.containers
  commands:
    - pip check
  requires:
    - python {{ python_min }}
    - pip

about:
  home: https://gitlab.com/burstcube/HealpixMap
  summary: Object-oriented healpy wrapper supporting multi-resolution maps
  license_file: LICENSE
  license: MIT

extra:
  recipe-maintainers:
    - titodalcanton
    - ickc
