{% set name = "mhealpy" %}
{% set version = "0.2.3" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/mhealpy-{{ version }}.tar.gz
  sha256: fce93ea7693613144cd79f1dad8c5dd5a0399c92953759e2fef82f98397d4c36

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - healpy
    # upstream doesn't constrain python, but healpy is not noarch and recent versions of healpy in conda-forge has py36 or upper binaries only
    - python >=3.6

test:
  imports:
    - mhealpy
    - mhealpy.containers
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://gitlab.com/burstcube/HealpixMap
  summary: Object-oriented healpy wrapper supporting multi-resolution maps
  license_file: LICENSE
  license: MIT

extra:
  recipe-maintainers:
    - ickc
