{% set name = "mhealpy" %}
{% set version = "0.2.2" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/mhealpy-{{ version }}.tar.gz
  sha256: 22c9cceb77c6da7118422443ced8f0f3a1d16b51b203898582030145f2209058

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - healpy
    # upstream doesn't constrain python, but healpy is not noarch and recent versions of healpy in conda-forge has py36 or upper binaries only
    - python >=3.6

test:
  imports:
    - mhealpy
    - mhealpy.containers
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://gitlab.com/burstcube/HealpixMap
  summary: Object-oriented healpy wrapper supporting multi-resolution maps
  license_file: LICENSE
  license: MIT

extra:
  recipe-maintainers:
    - ickc
