{% set name = "mhealpy" %}
{% set version = "0.2.1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/mhealpy-{{ version }}.tar.gz
  sha256: 6bf2a715cdeb71adddbd501a9eb3f5ac9b4e4f832711c38f496cf7b6ebf2e03f

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - healpy
    # upstream doesn't constrain python, but healpy is not noarch and recent versions of healpy in conda-forge has py36 or upper binaries only
    - python >=3.6

test:
  imports:
    - mhealpy
    - mhealpy.containers
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://gitlab.com/burstcube/HealpixMap
  summary: Object-oriented healpy wrapper supporting multi-resolution maps
  license_file: LICENSE
  license: MIT

extra:
  recipe-maintainers:
    - ickc
